Run build and test job even if lint step fails

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -31,6 +31,8 @@ jobs:
         run: pnpm lint
 
       - name: Run Build and Tests
+        # Will run the step even if lint step failed
+        if: success() || failure()
         run: pnpm run build-test
         env:
           CI: true
